======================================================= 1 error in 1.01s ======================================================== 
PS C:\Users\B730369\aws-reports\lib\lambda\test> python -m pytest patching_report_test.py
====================================================== test session starts ======================================================
platform win32 -- Python 3.10.12, pytest-8.3.4, pluggy-1.5.0
rootdir: C:\Users\B730369\aws-reports
configfile: pytest.ini
collected 0 items / 1 error

============================================================ ERRORS ============================================================= 
___________________________________ ERROR collecting lib/lambda/test/patching_report_test.py ____________________________________ 
ImportError while importing test module 'C:\Users\B730369\aws-reports\lib\lambda\test\patching_report_test.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
C:\Python310\lib\importlib\__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
patching_report_test.py:10: in <module>
    from lambda_handler import process_reports
E   ModuleNotFoundError: No module named 'lambda_handler'
==================================================== short test summary info ==================================================== 
ERROR patching_report_test.py
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! 
======================================================= 1 error in 0.97s ======================================================== 
PS C:\Users\B730369\aws-reports\lib\lambda\test> python -m pytest patching_report_test.py
====================================================== test session starts ======================================================
platform win32 -- Python 3.10.12, pytest-8.3.4, pluggy-1.5.0
rootdir: C:\Users\B730369\aws-reports
configfile: pytest.ini
collected 1 item

patching_report_test.py F                                                                                                  [100%]

=========================================================== FAILURES ============================================================ 
_____________________________________________________ test_process_reports ______________________________________________________ 

mock_s3_client = <MagicMock name='client' id='1723365539072'>

    def test_process_reports(mock_s3_client):
        # Mock the S3 client and responses
        mock_s3 = mock_s3_client.return_value
        mock_s3.get_object = mock.MagicMock(side_effect=mock_get_object)

        # Test process_reports function
        input_bucket = "op-cloudcustodian-reports"
        output_bucket = "op-patching-reports"
        ec2_report_key = "csv/ec2-all/ec2-all.csv"
        ami_report_key = "csv/all-amis/all-amis.csv"
        account_report_key = "csv/aws-account-data/latest/aws-account-data-report.csv"

>       result = process_reports(mock_s3, input_bucket, output_bucket, ec2_report_key, ami_report_key, account_report_key)        

patching_report_test.py:29:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

s3_client = <MagicMock name='client()' id='1723365538976'>, input_bucket = 'op-cloudcustodian-reports'
output_bucket = 'op-patching-reports', ec2_report_key = 'csv/ec2-all/ec2-all.csv', ami_report_key = 'csv/all-amis/all-amis.csv'   
account_report_key = 'csv/aws-account-data/latest/aws-account-data-report.csv'

    def process_reports(s3_client, input_bucket, output_bucket, ec2_report_key, ami_report_key, account_report_key):
        # Load EC2 report
        ec2_response = s3_client.get_object(Bucket=input_bucket, Key=ec2_report_key)
>       ec2_report = pd.read_csv(StringIO(ec2_response['Body'].read().decode('utf-8')))
E       AttributeError: 'str' object has no attribute 'decode'. Did you mean: 'encode'?

..\op_patching_report\main.py:10: AttributeError
==================================================== short test summary info ==================================================== 
FAILED patching_report_test.py::test_process_reports - AttributeError: 'str' object has no attribute 'decode'. Did you mean: 'encode'?
